# Generated by Django 6.0.3 on 2026-04-14 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('is_dangerous', models.BooleanField(default=False, verbose_name='Dangerous/Agressive component')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product name')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('recommended_for_skin', models.CharField(max_length=100, verbose_name='Recommended for this skin type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='products', to='skinmatch.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Reasons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendee_in', to='skinmatch.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(choices=[('dry', 'сухая'), ('oily', 'жирная'), ('combo', 'комбинированная'), ('normal', 'нормальная')], max_length=10, verbose_name='Skin type')),
                ('primary_concern', models.CharField(blank=True, max_length=100, verbose_name='Main problem(acne,wrincles ect.)')),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
