# Generated by Django 6.0.3 on 2026-04-15 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinmatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price', 'brand', 'name']},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cleanser', 'Cleanser'), ('toner', 'Toner'), ('serum', 'Serum'), ('moisturizer', 'Moisturizer'), ('sunscreen', 'Sunscreen'), ('mask', 'Mask'), ('foundation', 'Foundation'), ('concealer', 'Concealer'), ('blush', 'Blush'), ('bronzer', 'Bronzer')], default='cleanser', max_length=30, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='concern_focus',
            field=models.CharField(blank=True, help_text='Comma separated concerns like acne,dehydration,pigmentation', max_length=150, verbose_name='Concerns'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_budget_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended_for_face_shape',
            field=models.CharField(blank=True, help_text='Comma separated face shapes like oval,round', max_length=100, verbose_name='Face shapes'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='is_dangerous',
            field=models.BooleanField(default=False, verbose_name='Dangerous ingredient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_for_skin',
            field=models.CharField(choices=[('dry', 'Dry'), ('oily', 'Oily'), ('combo', 'Combination'), ('normal', 'Normal'), ('all', 'All skin types')], default='all', max_length=10, verbose_name='Recommended skin type'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_in', to='skinmatch.product'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skinprofile',
            name='primary_concern',
            field=models.CharField(blank=True, max_length=100, verbose_name='Main problem'),
        ),
        migrations.AlterField(
            model_name='skinprofile',
            name='skin_type',
            field=models.CharField(choices=[('dry', 'Dry'), ('oily', 'Oily'), ('combo', 'Combination'), ('normal', 'Normal')], max_length=10, verbose_name='Skin type'),
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='analyses/')),
                ('detected_skin_type', models.CharField(choices=[('dry', 'Dry'), ('oily', 'Oily'), ('combo', 'Combination'), ('normal', 'Normal')], max_length=10)),
                ('detected_face_shape', models.CharField(choices=[('oval', 'Oval'), ('round', 'Round'), ('square', 'Square'), ('heart', 'Heart'), ('oblong', 'Oblong')], max_length=10)),
                ('detected_concern', models.CharField(blank=True, max_length=100)),
                ('budget_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_selected_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('analysis_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='skinmatch.analysissession'),
        ),
    ]
